#!/bin/bash

set -eu

BUILD_ROOT=$(pwd)

mkdir -p build/$BUILD_NAME
cd build/$BUILD_NAME

cmake -DUSE_OPENSSL=ON -DBUILD_STATIC=ON $BUILD_ROOT
make

mkdir -p $BUILD_ROOT/target/$BUILD_NAME
cp src/rtty $BUILD_ROOT/target/$BUILD_NAME