name: rtty

services:
  u24:
    container_name: u24
    hostname: u24
    image: ccr.ccs.tencentyun.com/muse/build:rtty-noble
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: noble
    volumes:
      - .:/ws
      - ./misc/build-main:/build

  u22:
    container_name: u22
    hostname: u22
    image: ccr.ccs.tencentyun.com/muse/build:rtty-jammy
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: jammy
    volumes:
      - .:/ws
      - ./misc/build-main:/build

  alpine:
    container_name: alpine
    hostname: alpine
    image: ccr.ccs.tencentyun.com/muse/build:rtty-alpine
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: alpine
    volumes:
      - .:/ws
      - ./misc/build-main:/build
  
  alpine-static:
    container_name: alpine
    hostname: alpine
    image: ccr.ccs.tencentyun.com/muse/build:rtty-alpine
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: alpine-static
      BUILD_STATIC: yes
    volumes:
      - .:/ws
      - ./misc/build-main:/build
  
  u24-static:
    container_name: u24
    hostname: u24
    image: ccr.ccs.tencentyun.com/muse/build:rtty-noble
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: noble-static
      BUILD_STATIC: yes
    volumes:
      - .:/ws
      - ./misc/build-main:/build

  centos7:
    container_name: centos7
    hostname: centos7
    image: ccr.ccs.tencentyun.com/muse/build:rtty-centos7
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: centos7
    volumes:
      - .:/ws
      - ./misc/build-centos7:/build

  centos7-static:
    container_name: centos7
    hostname: centos7
    image: ccr.ccs.tencentyun.com/muse/build:rtty-centos7
    restart: no
    command: ["/build"]
    working_dir: "/ws"
    environment:
      BUILD_NAME: centos7-static
      BUILD_STATIC: yes
    volumes:
      - .:/ws
      - ./misc/build-centos7:/build
