name: build
on: [push, pull_request]
jobs:
  build-u24:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: build image
        run: |
          docker build . \
            -t ghcr.io/makenv/rtty:ubuntu-24.04 \
            -f misc/ubuntu-24.04/Dockerfile
          docker push ghcr.io/makenv/rtty:ubuntu-24.04
            
          

